### ISSUE TITLE
Prepare for announcement

### ISSUE THREAD

**Issue by worm2fed** [union-platform/website#24]
- [x] Home button do not have much sense now
<img width="159" alt="image" src="https://user-images.githubusercontent.com/6579275/200120005-ca4f1f00-5992-4035-91ec-fce6aeabbdf5.png">

- [x] Change "Get in touch" to point to [telegram chat](https://t.me/unionapp_cc_dev)
<img width="257" alt="image" src="https://user-images.githubusercontent.com/6579275/200120543-0959ad27-af91-4495-9baf-703dbeafc933.png">

- [ ] Fix white vertical lines in animation
<img width="225" alt="image" src="https://user-images.githubusercontent.com/6579275/200119570-372f4334-d432-4f04-8502-1dc0d897811e.png">

- [x] Change text on main screen 
  `Find an activity you like, join an interesting project or create your own.` -> `Find your labor of love, join an interesting project or create your own`

- [x] Change meaningless subtitle
   `coming soon, be in touch`
<img width="939" alt="image" src="https://user-images.githubusercontent.com/20303265/163960531-53de10df-2275-45cf-8155-9abb41f4ecd5.png">

- [x] Hide system tray (with battery, cellular, etc.)
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/6579275/200120091-15983d66-b15c-41d2-94c1-327d6ddf8ff5.png">

- [x] Change text in features:
  1. Activity matters
      Finding a new project just got easier: apply filters and find it.
  2. Team is the strength
      Do you want to find creative professionals in your area? Share an idea and build your dream team.
  3. Start a new project
      Have an idea for a business, social activity or want to improve our world? Initiate a project!
  4. Find like-minded people
      Find new team members with the right mindset and skills.

- [x] Change contact info in footer
  Should be ui-lib, github, [telegram chat](https://t.me/unionapp_cc_dev)
<img width="283" alt="image" src="https://user-images.githubusercontent.com/6579275/200120400-c576abad-1172-45b8-b09e-9697f852a9d7.png">

- [x] Change social medio in footer
  Should be [telegram channel](https://t.me/unionapp_cc)
<img width="211" alt="image" src="https://user-images.githubusercontent.com/6579275/200120505-879f007b-ccaa-42f0-9cf0-1e20d2cdb51e.png">

- [x] Hide sitemap in footr
<img width="269" alt="image" src="https://user-images.githubusercontent.com/6579275/200120473-f1b13a0a-2036-49f4-a467-043e9e85f24d.png">

- [x] Add .webp and other generated image formats

**Comment by rexolion** [comment]
- Add .webp and other generated image formats
